#!/bin/bash
#asking the user informations about the scripts
IFS=
echo "Hello there !"
echo
echo "what is your file name of the script you want to create ? (dont'use whitespace)"
read -p "file name : " file_name
echo
echo "Thx ! and what command do we need to execute in $file_name ?"
echo
read -r -e -p "Command to add : " command_line
#we create the file with the shebang first  and add the command
echo '#!/bin/bash' > $file_name
echo "$command_line" >> $file_name
echo
echo "Your script is now created !"
echo
#we ask the user informations ahout the created script to document it in README.md
echo "What will you script do ? (USE ONLY WHITESPACE AS A DELIMITER)"
read -r -e -p "filename & Usage : " script_documentation
echo "$script_documentation" >> README.md
echo
echo "The README.md file has been updated !"
echo
#Changing the permissions on the freshly created script
chmod 744 $file_name
echo "Permission to exectue the script havec now been granted ! "
echo
#Adding the  file to the repo
echo "let\'s add your work to your repositry"
echo
git add $file_name
echo "what is your commit message ?"
read -r -e  -p "commit_message : " commit_message
git commit -m "$commit_message"
git push
echo
echo "Everything's fine, time to execute order 66 !"
echo
sleep 1
#execution of the freshly created script
./$file_name
#restoring the IFS value to its default
unset IFS
echo "That's all Folks !"
