#!/bin/bash
#Setting the Input Field Separator to empty
IFS=
#asking the user informations about the scripts
echo "Hello there !"
echo
read -p "do you need to create a file for you excercise ? Y or N : " -n 1 -r secondary_file_creation
echo
if [[ $secondary_file_creation =~ ^[Yy]$ ]]
then
	read -r -e -p "please type the name of the file you need to create : " secondary_file_name
	echo
	read -p "does your file need to be stored somewhere else ? Y or N : " -n 1 -r secondary_file_storage
	if [[ $secondary_file_storage =~ ^[Yy]$ ]]
	then
		read -r -e -p "please type the ABSOLUTE path for your file : " secondary_file_path
		touch $secondary_file_name $secondary_file_path
	fi
	if [[ ! $secondary_file_storage =~ ^[Yy]$ ]]
	then
		echo
		echo "let's create the file in this directory"
		touch $secondary_file_name
	fi
fi
if [[ ! $secondary_file_creation =~ ^[Yy]$ ]]
then
	echo "ok then, let's push things forward..."
	echo
fi
read -p "what is the file name of the script you want to create ? (don't use whitespace) : " file_name
echo
read -r -e -p "Thx ! now, type the command we need to execute in $file_name : " command_line
#we create the file with the shebang first  and add the command
echo '#!/bin/bash' > $file_name
echo "$command_line" >> $file_name
echo
echo "Your script is now created !"
echo
#asking if the script needs to be copied somewhere else
read -p "do you need a copy of this script somewhere else ? Y or N : " -n 1 -r copy_reply
echo
if [[ $copy_reply =~ ^[Yy]$ ]]
then
	echo "please type the ABSOLUTE path ! (starting from /)"
	echo
	read -r  -e -p "where do we copy this script ? : " copy_path
	mkdir $copy_path
	cp $file_name /tmp
fi
if [[ ! $copy_reply =~ ^[Yy]$ ]]
then
	echo "Ok, let's skip tahat part, and carry on, shall we ?"
fi
echo
#we ask the user informations ahout the created script to document it in README.md
echo "Please Documentation is important, consider to fill the next part as if you don't know what all this was about"
echo
echo "What will your script do ? (expected format :  $file_name ---> DESCRIPTION )"
read -r -e -p "filename & Usage : " script_documentation
echo -n -e '\n' >> README.md
echo "$script_documentation" >> README.md
echo -n -e '\n' >> README.md
echo
echo "The README.md file has been updated !"
echo
#Changing the permissions on the freshly created script
echo "what specific permissions do you want to apply to this script ?"
chmod 744 $file_name
echo "Permission for $file_name has been now changed to 744 ! ( User : -rwx ; Group : r-- ; Other : r--  )"
echo
#Adding the  file to the repo
echo "let's now add this script to your repositry"
echo
git add $file_name
echo "what is your commit message ?"
read -r -e  -p "commit_message : " commit_message
echo
git commit -m "$commit_message"
echo
git push
echo
echo "Everything seems fine, it's time to execute the $command_line command you've put in $file_name :"
echo
#execution of the freshly created script
./$file_name
#restoring the IFS value to its default
unset IFS
#Congratulating the user ! all tasks are now completed
echo
echo "Awsome ! we're done here, you can now review your code on holberton's intrant. You sure did an amazing job today !"
