#!/bin/bash
#Setting the Input Field Separator to empty
IFS=
#asking the user informations about the scripts
echo "Hello there !"
echo
echo "what is the file name of the script you want to create ? (dont'use whitespace)"
read -p "file name : " file_name
echo
echo "Thx ! and what command do we need to execute in $file_name ?"
echo
read -r -e -p "Command to add : " command_line
#we create the file with the shebang first  and add the command
echo '#!/bin/bash' > $file_name
echo "$command_line" >> $file_name
echo
echo "Your script is now created !"
echo
#we ask the user informations ahout the created script to document it in README.md
echo "What will your script do ? (expected format :  $file_name ---> DESCRIPTION )"
read -r -e -p "filename & Usage : " script_documentation
echo -n -e '\n' >> README.md
echo "$script_documentation" >> README.md
echo
echo "The README.md file has been updated !"
echo
#Changing the permissions on the freshly created script
chmod 744 $file_name
echo "Permission for $file_name has been now changed to 744 ! ( User : -rwx ; Group : r-- ; Other : r--  )"
echo
#Adding the  file to the repo
echo "let's now add this script to your repositry"
echo
git add $file_name
echo "what is your commit message ?"
read -r -e  -p "commit_message : " commit_message
echo
git commit -m "$commit_message"
echo
git push
echo
echo "Everything seems fine, it's time to execute the $command_line command you've put in $file_name :"
echo
#execution of the freshly created script
./$file_name
#restoring the IFS value to its default
unset IFS
#Congratulating the user ! all tasks are now completed
echo
echo "Awsome ! we're done here, you can now review your code on holberton's intrant. You sure did an amazing job today !"
